apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cargo-types-db-container
  name: cargo-types-db-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cargo-types-db-container
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cargo-types-db-container
    spec:
      containers:
        - args:
            - -p
            - "5433"
          env:
            - name: POSTGRES_DB
              value: cargo_types_db
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: cargo-types-db-container
          ports:
            - containerPort: 5433
          resources: {}
      restartPolicy: Always
status: {}
